api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
#    exception_to_status:
#        App\Exceptions\ExpiredSessionException: 401
